import { PRODUCTS, releasesPageUrl, type ReleasesResponse } from '../data/products';
import { downloadTarget } from './downloads';

// Cloudflare Pages rules for the paths the Worker used to answer: the old
// /api/releases URL serves the static JSON, and every /download/<platform>
// is a 302 to the asset, store page or channel known at build time, falling
// back to the releases page like the Worker did.
export function renderRedirects({ products }: ReleasesResponse): string {
  const lines = [
    '# Generated by the build from /api/releases.json; edits are overwritten.',
    '/api/releases /api/releases.json 200',
  ];
  for (const product of PRODUCTS) {
    const info = products[product.id] ?? { status: 'error', error: 'missing', pageUrl: releasesPageUrl(product) };
    for (const { platform } of product.downloads) {
      const target = downloadTarget(platform, info);
      lines.push(`/download/${platform} ${target} 302`, `/download/${platform}/ ${target} 302`);
    }
  }
  return `${lines.join('\n')}\n`;
}
