import {
  ArrowDownToLine,
  ArrowLeft,
  ArrowUpRight,
  Blocks,
  CalendarDays,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  CloudSync,
  CodeXml,
  Compass,
  Database,
  DatabaseBackup,
  FlaskConical,
  Folders,
  Funnel,
  Globe,
  History,
  House,
  ImagePlus,
  Images,
  Info,
  Languages,
  LayoutGrid,
  ListChecks,
  Megaphone,
  MegaphoneOff,
  MessageSquareText,
  MessagesSquare,
  Minus,
  Monitor,
  Network,
  Package,
  Palette,
  Pause,
  Plane,
  Play,
  Repeat2,
  Scale,
  ShieldCheck,
  SlidersHorizontal,
  Smartphone,
  Sparkles,
  Sticker,
  Tag,
  Target,
  TextCursorInput,
  Users,
  WholeWord,
  Workflow,
  X,
  type IconNode,
} from 'lucide';
import { BRAND_ICONS } from './brands';

// Components ask for icons by role, so swapping a glyph happens here once.
const UI_ICONS = {
  // Actions and navigation
  'arrow-left': ArrowLeft,
  'chevron-down': ChevronDown,
  'chevron-left': ChevronLeft,
  'chevron-right': ChevronRight,
  close: X,
  download: ArrowDownToLine,
  external: ArrowUpRight,
  check: Check,
  minus: Minus,
  info: Info,
  sparkles: Sparkles,
  pause: Pause,
  play: Play,
  globe: Globe,
  compass: Compass,

  // Site sections
  home: House,
  products: LayoutGrid,
  features: ListChecks,
  screenshots: Images,
  privacy: ShieldCheck,

  // Products and releases
  phone: Smartphone,
  desktop: Monitor,
  version: Tag,
  license: Scale,
  source: CodeXml,
  releases: Package,
  workflow: Workflow,
  beta: FlaskConical,
  testflight: Plane,
  calendar: CalendarDays,
  'image-pending': ImagePlus,

  // Community
  channel: Megaphone,
  group: Users,
  chat: MessagesSquare,

  // Feature themes
  translate: Languages,
  filter: Funnel,
  repeat: Repeat2,
  spacing: WholeWord,
  'ads-off': MegaphoneOff,
  sync: CloudSync,
  text: TextCursorInput,
  messages: MessageSquareText,
  folders: Folders,
  sticker: Sticker,
  palette: Palette,
  network: Network,
  backup: DatabaseBackup,

  // Policy topics
  scope: Target,
  data: Database,
  settings: SlidersHorizontal,
  services: Blocks,
  history: History,
} satisfies Record<string, IconNode>;

export const ICONS: Record<IconName, IconNode> = { ...UI_ICONS, ...BRAND_ICONS };

export type IconName = keyof typeof UI_ICONS | keyof typeof BRAND_ICONS;
